### ISSUE TITLE
Can not get email notification

### ISSUE THREAD

**Issue by VictorTrapenok** [VersusControl/versus-incident#20]
Hi.
I run this project in Kubernetes and try to use for email notifications.
  
On Api call is answer `{"status":"Incident created"}` but email not come and no any errors in pod logs.

Where can be a problem?

```bash
curl -X POST http://d1-versus.unifie.io/api/incidents    -H "Content-Type: application/json"   -d '{
    "Logs": "[ERROR] This is an error log from User Service that we can obtain using Fluent Bit.",
    "ServiceName": "order-service"
  }'
{"status":"Incident created"}
```

I run it with this yaml specs:

```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  namespace: dp-1-191
  name: versus-config
data:
  config.yaml: |-
    name: verus
    port: 3000
  email_message.tmpl: |
    *Error in {{.ServiceName}}*
    ----------
    Error Details:
    ```
    {{.Logs}}
    ```
  slack_message.tmpl: |
    *Critical Error in {{.ServiceName}}*
    ----------
    Error Details:
    ```
    {{.Logs}}
    ```
    ----------
    Owner <@{{.UserID}}> please investigate

---
apiVersion: v1
kind: Service
metadata:
  name: versus-service
  namespace: dp-1-191
  labels:
    app: versus-service
spec:
  type: ClusterIP
  sessionAffinity: None
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
  selector:
    app.kubernetes.io/name: versus-incident
    app-type: versus-incident

---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: dp-1-191
  name: versus-incident
  labels:
    app-type: versus-incident
    app.kubernetes.io/name: versus-incident
spec:
  replicas: 2
  selector:
    matchLabels:
      app-type: versus-incident
      app.kubernetes.io/name: versus-incident
  template:
    metadata:
      labels:
        app-type: versus-incident
        app.kubernetes.io/name: versus-incident
    spec:
      volumes:
        - name: versus-config
          configMap:
            name: versus-config
      containers:
        - name: versus
          image: ghcr.io/versuscontrol/versus-incident:v1.0.0
          ports:
            - containerPort: 3000
          livenessProbe:
            httpGet:
              path: /healthz
              port: 3000
          env:
            - name: PORT
              value: '3000'
            - name: EMAIL_TEMPLATE_PATH
              value: config/email_message.tmpl 
            - name: DEBUG_BODY
              value: 'false'
            - name: EMAIL_ENABLE
              value: 'true'
            - name: EMAIL_SUBJECT
              value: test
            - name: EMAIL_TO
              value: XXXX@XX.XX
            - name: SLACK_ENABLE
              value: 'false'
            - name: SMTP_HOST
              value: smtp.yandex.ru
            - name: SMTP_PASSWORD
              value: XXXXXXXXXXXXXXXXXXX
            - name: SMTP_PORT
              value: '587'
            - name: SMTP_USERNAME
              value: XXXX@XX.XX
            - name: SNS_ENABLE
              value: 'false'
            - name: TELEGRAM_ENABLE
              value: 'false'
          volumeMounts:
            - name: versus-config
              mountPath: /app/config/config.yaml
              subPath: config.yaml
            - name: versus-config
              mountPath: /app/config/slack_message.tmpl
              subPath: slack_message.tmpl
            - name: versus-config
              mountPath: /app/config/email_message.tmpl
              subPath: email_message.tmpl
```
